apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-match-expression
  labels:
    app: frontend
  annotations:
    description: nginx replica set match expression joji belajar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: nodejs-web
          image: aureezzhenx/$NAMA_IMAGE:v1.$VERSION_BUILD ## SED ENV BEST PRACTICE (not using latest image)
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service-frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: k8s-jenkins-deploy
