apiVersion: v1
kind: Namespace
metadata:
  name: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
  labels:
    app: backend
  annotations:
    description: backend image deployment joji belajar
spec:
  selector:
    matchLabels:
      app: backend
    matchExpressions:
      - key: app
        operator: In
        values:
          - backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: nodejs-web
          image: aureezzhenx/$NAMA_IMAGE:v1.$VERSION_BUILD
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 1000Mi

---

apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa-autoscaller
  namespace: backend
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70