apiVersion: v1
kind: Namespace
metadata:
  name: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
  labels:
    app: frontend
  annotations:
    description: frontend image deployment joji belajar
spec:
  selector:
    matchLabels:
      app: frontend
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: nodejs-web
          image: aureezzhenx/$NAMA_IMAGE:v1.$VERSION_BUILD
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service-frontend-loadbalancer
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa-autoscaller
  namespace: frontend
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70