apiVersion: v1
kind: Namespace
metadata:
  name: frontend

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
  annotations:
    description: frontend image replica set match expression joji belajar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: nodejs-web
          image: aureezzhenx/$NAMA_IMAGE:v1.$VERSION_BUILD
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service-frontend-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000